//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDERDETAIL
    {
        public long ORDERITEM_ID { get; set; }
        public Nullable<long> ORDER_ID { get; set; }
        public Nullable<int> ITEMID { get; set; }
        public Nullable<int> QUANTITY { get; set; }
    
        public virtual ITEM ITEM { get; set; }
        public virtual ORDER ORDER { get; set; }
    }
}
